version: 2.1

commands: 
  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
            python3 ./deps/readies/sbin/system-setup.py

jobs:
  build-and-test:
      docker:
        - image: 'ubuntu:bionic'
      steps:
        - setup-executor
        - checkout
        - setup-automation
        - run:
            name: Install Redis
            command: ./deps/readies/bin/getredis --version 6
        - run:
            name: Tests
            command: make Tests

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test:
          <<: *on-any-branch
